# Generated by Django 3.0.4 on 2020-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_thyrocare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyrocare',
            name='BUN',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='CS',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='Ca',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='UA',
            field=models.CharField(max_length=4),
        ),
    ]
