# Generated by Django 3.0.4 on 2020-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_auto_20200421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyrocare',
            name='BUN',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='CS',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='Ca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thyrocare',
            name='UA',
            field=models.CharField(max_length=10),
        ),
    ]
